-- use rxflow;
select *
from users;
-- update users
-- set image = 'http://localhost:8081/rxflow_backend_war_exploded/images/default.png'
-- where id = 1;
-- UPDATE users
-- set role = 'ROLE_ADMIN'
-- where id = 1;
-- ***************
-- ***************
-- *********************************** MYSQL ***********************************
-- CREATE TABLE users(
--     id int not null primary key auto_increment,
--     username varchar(100) not null unique,
--     password varchar(255) not null,
--     email varchar(255),
--     phone varchar(30) not null default '000000000000000',
--     name varchar(255) not null,
--     role varchar(20) not null default 'ROLE_USER',
--     image varchar(255) not null,
--     gender varchar(20) not null default 'Not Selected',
--     address json not null default (JSON_OBJECT('line1', '', 'line2', '')),
--     dob varchar(20) not null default 'Not Selected'
-- );
-- CREATE TABLE doctors(
--     id int not null primary key auto_increment,
--     user_id int not null,
--     speciality varchar(50) not null,
--     degree varchar(50) not null,
--     experience varchar(10) not null,
--     about text not null,
--     available boolean default true,
--     fees float default 0.0,
--     slots_booked JSON NOT NULL,
--     foreign key (user_id) references users(id)
-- );
-- CREATE TABLE IF NOT EXISTS appointments(
--     id int not null primary key auto_increment,
--     user_id int not null,
--     docId int not null,
--     slotDate varchar(50) not null,
--     slotTime varchar(50) not null,
--     userData JSON not null,
--     docData JSON not null,
--     amount float not null,
--     date int not null,
--     cancelled boolean default false,
--     payment boolean default false,
--     isCompleted boolean default false,
--     foreign key (user_id) references users(id),
--     foreign key (docId) references doctors(id)
-- );
-- ***************
-- ***************
-- *********************************** POSTGRESQL ***********************************
-- CREATE TABLE users(
--     id serial not null primary key,
--     username varchar(100) not null unique,
--     password varchar(255) not null,
--     email varchar(255),
--     phone varchar(30) not null default '000000000000000',
--     name varchar(255) not null,
--     role varchar(20) not null default 'ROLE_USER',
--     image varchar(255) not null,
--     gender varchar(20) not null default 'Not Selected',
--     address jsonb not null default '{"line1": "", "line2": ""}'::jsonb,
--     dob varchar(20) not null default 'Not Selected'
-- );
-- CREATE TABLE doctors(
--     id serial not null primary key,
--     user_id int not null,
--     speciality varchar(50) not null,
--     degree varchar(50) not null,
--     experience varchar(10) not null,
--     about text not null,
--     available boolean default true,
--     fees float default 0.0,
--     slots_booked jsonb NOT NULL,
--     foreign key (user_id) references users(id)
-- );
-- CREATE TABLE appointments(
--     id serial not null primary key,
--     user_id int not null,
--     doctor_id int not null,
--     slot_date varchar(20) not null,
--     slot_time varchar(20) not null,
--     amount float not null,
--     date varchar(20) not null,
--     cancelled boolean default false,
--     payment boolean default false,
--     is_completed boolean false,
--     foreign key (user_id) references users(id),
--     foreign key (doctor_id) references doctors(id)
-- )